FROM continuumio/miniconda3
SHELL ["/bin/bash", "-c"]
RUN apt update
RUN apt install vim -y

COPY .docker/environment.yml .
RUN conda env create --file environment.yml

RUN useradd -m econ
USER econ

COPY .docker/.bashrc /home/econ/.bashrc
ENV PATH "/opt/conda/envs/econ/bin:$PATH"
